kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: oes-analysis-job
spec:
  metrics:
    - name: oes-analysis-job
      count: 1
      provider:
        isd:
          Gate_URL: https://ds312.isd-dev.opsmx.net
          Application: testapp
          LifetimeHours: "0.5"
