apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testapp2
spec:
  metrics:
    - name: testapp2
      provider:
        ISD:
	  Gate_url: "https://ds312.isd-dev.opsmx.net/"
	  Application: "testapp"
	  Baseline_start_time: "2022-07-29T13:15:00Z"
	  Canary_start_time: "2022-07-29T13:15:00Z"
	  LifetimeHours: "0.5"
	  Threshold:
	    Pass: 80
	    Marginal: 60
